version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    container_name: requestapp_database
    volumes:
      - .docker/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: requestapp

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "8080:80"
    depends_on:
      - pgsql